<?php

namespace Woe\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    public function findByKeywords(array $keywords)
    {
        $query = $this->createQueryBuilder('event')
            ->innerJoin('event.keywords', 'k')
            ->where('k.name IN (:keywords)')
            ->groupBy('event.id')
            ->having("COUNT(event.id) = :count")
            ->orderBy('event.date')
            ->setParameters(array(
                'keywords' => $keywords,
                'count' => count($keywords)
            ));

        return $query->getQuery()->getResult();
    }

    public function findAllActiveSortedByDate()
    {
        $query = $this->createQueryBuilder('event')
            ->where('event.date > :date')
            ->setParameter('date', new \DateTime('now'))
            ->orderBy('event.date');

        return $query->getQuery()->getResult();
    }
}
