<?php

namespace Woe\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends EntityRepository
{
    /**
     * Find keyword by name or create new if it does not exist
     *
     * @param string $name
     * @return Keyword
     */
    public function findOrCreateKeyword($name)
    {
        $keyword = $this->findOneBy(array(
            'name'      => $name,
        ));

        if (is_null($keyword)) {
            $keyword = new Keyword();
            $keyword->setName($name);
        }

        return $keyword;
    }
}
