<?php

namespace Woe\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
    /**
     * Find location by name, address and City or create new if it does not exist
     *
     * @param string $name
     * @param string $address
     * @param City $city
     * @return Location
     */
    public function findOrCreateLocation($name, $address, $city)
    {
        $location = $this->findOneBy(array(
            'name'      => $name,
            'address'   => $address,
            'city'      => $city->getId()
        ));

        if (is_null($location)) {
            $location = new Location();
            $location->setName($name);
            $location->setAddress($address);
            $location->setCity($city);
        }

        return $location;
    }
}
